[package]
name = "solana-account"

authors = { workspace = true }
description = "Solana Account type"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
version = "4.3.1"

[features]
bincode = ["dep:bincode", "dep:solana-sysvar", "serde"]
serde = [
    "bitflags/serde",
    "dep:serde",
    "dep:serde_bytes",
    "serde/derive",
    "serde/rc",
    "solana-pubkey/serde"
]
testkit = ["bincode"]
wincode = ["bincode", "dep:wincode", "solana-pubkey/wincode"]

[dependencies]
bincode = { workspace = true, optional = true }
bitflags = { workspace = true }
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
solana-account-info = { workspace = true }
solana-clock = { workspace = true }
solana-instruction-error = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-sysvar = { workspace = true, features = ["bincode"], optional = true }
thiserror = { workspace = true }
wincode = { workspace = true, features = ["alloc"], optional = true }

[dev-dependencies]
solana-account = { path = ".", features = ["testkit"] }
solana-pubkey = { workspace = true, features = ["std"] }

[lints]
workspace = true
